spring:
  mvc:    favicon:      enabled: false
  servlet:
    multipart:
      max-file-size : 50MB
      max-request-size: 50MB
  redis:
        lettuce:
            pool:
                max-active: 10
                max-idle: 10
                min-idle: 2
        port: 6379
        host: 127.0.0.1
        channel: foo    
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 881218558153-ndr868i68rlofoo4l2gb488ksabi5q23.apps.googleusercontent.com
            client-secret: kq6zIo0myJotHK5_0irhtYnW
  freemarker:
    cache: false
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    enabled: true
  datasource:
      driverClassName : net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      url: "jdbc:log4jdbc:mariadb://moimdev.cxz28d3n4hpj.ap-northeast-2.rds.amazonaws.com:3306/fruit"
      #url: "jdbc:mariadb://moimdev.cxz28d3n4hpj.ap-northeast-2.rds.amazonaws.com:3306/jpatest"
      username: csj2702
      password: tjdwns2702
  jpa:
        show-sql: false
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                format_sql: true
  jackson:
    time-zone: UTC
    serialization:
                  WRITE_DATES_AS_TIMESTAMPS : false
                  FAIL_ON_EMPTY_BEANS : false
                  
logging:
        level:
              com:
                  devson: 
                          pagination: debug
                         
server:
    port: 8080
   
    servlet:
        
        cookie:
          http-only: true
        session:
         tracking-modes: cookie

moimImagePath: C:/dayary/moim/image
communityImagePath : C:/dayary/community/image
userprofileImagePath : C:/dayary/user/image

app:
      jwtSecret : JWTSuperSecretKey
      jwtExpirationInMs : 604800000
      
facebook:
  client:
    clientId: <your-client-id>
    clientSecret: <your-secret>
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me?fields=id, name, email, picture

google :
  client :
    clientId : 881218558153-ndr868i68rlofoo4l2gb488ksabi5q23.apps.googleusercontent.com
    clientSecret: kq6zIo0myJotHK5_0irhtYnW
    accessTokenUri: https://www.googleapis.com/oauth2/v4/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
    clientAuthenticationScheme: form
    scope:
    - email
    - profile
  resource:
    userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo

    
            
mail:
    host: smtp.gmail.com
    port: 587
    username: fruitteamsup@gmail.com
    password: tjdwns2702!@
    protocol: smtp
    default-encoding: UTF-8
    smtp: 
      start-tls-enable: true 
      auth: true