spring:
  mvc:    favicon:      enabled: false
  servlet:
    multipart:
      max-file-size : 50MB
      max-request-size: 50MB
        
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 881218558153-ndr868i68rlofoo4l2gb488ksabi5q23.apps.googleusercontent.com
            client-secret: kq6zIo0myJotHK5_0irhtYnW
  freemarker:
    cache: false
  devtools:
    livereload:
      enabled: true
  thymeleaf:
        cache: false

  datasource:
      url: "jdbc:mariadb://moimdev.cxz28d3n4hpj.ap-northeast-2.rds.amazonaws.com:3306/jpatest"
      username: csj2702
      password: tjdwns2702
  jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                format_sql: true
  jackson:
    time-zone: UTC
    serialization:
                  WRITE_DATES_AS_TIMESTAMPS : false
                  FAIL_ON_EMPTY_BEANS : false
                  
logging:
        level:
              com:
                  devson: 
                          pagination: debug
                         
server:
    port: 8080
   
    servlet:
        
        cookie:
          http-only: true
        session:
         tracking-modes: cookie

moimImagePath: C:/dayary/moim/image
communityImagePath : C:/dayary/community/image

app:
      jwtSecret : JWTSuperSecretKey
      jwtExpirationInMs : 604800000